/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectLink: typeof import('./components/DirectLink.vue')['default']
    DynamicChildren: typeof import('./components/DynamicChildren.vue')['default']
    Exercise: typeof import('./components/Exercise.vue')['default']
    File: typeof import('./components/File.vue')['default']
    Folder: typeof import('./components/Folder.vue')['default']
    Forum: typeof import('./components/Forum.vue')['default']
    Leaf: typeof import('./components/Leaf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./components/SelectBox.vue')['default']
    UpdateIcon: typeof import('./components/UpdateIcon.vue')['default']
    Video: typeof import('./components/Video.vue')['default']
  }
}
