// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DirectLink: typeof import('./components/DirectLink.vue')['default']
    DynamicChildren: typeof import('./components/DynamicChildren.vue')['default']
    Exercise: typeof import('./components/Exercise.vue')['default']
    File: typeof import('./components/File.vue')['default']
    Folder: typeof import('./components/Folder.vue')['default']
    Forum: typeof import('./components/Forum.vue')['default']
    Leaf: typeof import('./components/Leaf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./components/SelectBox.vue')['default']
    UpdateIcon: typeof import('./components/UpdateIcon.vue')['default']
    Video: typeof import('./components/Video.vue')['default']
  }
}
